version: '3.9'

services:
  epilepsy-science:
    platform: linux/amd64  # Force x86_64 architecture
    env_file:
      - dev.env
    image: neuronova/epilepsy-science:latest
    volumes:
      - ./data:/app/data
      - /Users/nishant/Dropbox/Sinha/Lab/Research/projects/discover/epilepsy/epi_t3_iEEG/data/BIDS:/app/data/BIDS
    container_name: epilepsy-science
    build:
      context: .
      dockerfile: ./Dockerfile